"""v2.1: sante profil, vaccinations, medecin lat/lng

Revision ID: 691a6cfe4ea2
Revises: 76e541375686
Create Date: 2026-07-07 16:46:50.334379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691a6cfe4ea2'
down_revision: Union[str, None] = '76e541375686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sante_profils',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('groupe_sanguin', sa.Enum('a_pos', 'a_neg', 'b_pos', 'b_neg', 'ab_pos', 'ab_neg', 'o_pos', 'o_neg', name='groupesanguin'), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('antecedents', sa.JSON(), nullable=False),
    sa.Column('maladies_chroniques', sa.JSON(), nullable=False),
    sa.Column('traitements_en_cours', sa.Text(), nullable=True),
    sa.Column('medecin_traitant_id', sa.UUID(), nullable=True),
    sa.Column('contact_urgence_nom', sa.String(length=100), nullable=True),
    sa.Column('contact_urgence_prenom', sa.String(length=100), nullable=True),
    sa.Column('contact_urgence_telephone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medecin_traitant_id'], ['medecin_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('vaccination_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sante_profil_id', sa.UUID(), nullable=False),
    sa.Column('vaccin', sa.String(length=100), nullable=False),
    sa.Column('date_administration', sa.Date(), nullable=False),
    sa.Column('prochain_rappel', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['sante_profil_id'], ['sante_profils.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccination_entries_sante_profil_id'), 'vaccination_entries', ['sante_profil_id'], unique=False)
    op.add_column('medecin_profiles', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('medecin_profiles', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medecin_profiles', 'longitude')
    op.drop_column('medecin_profiles', 'latitude')
    op.drop_index(op.f('ix_vaccination_entries_sante_profil_id'), table_name='vaccination_entries')
    op.drop_table('vaccination_entries')
    op.drop_table('sante_profils')
    # ### end Alembic commands ###
