"""partial unique index active rdv per creneau

Revision ID: c84cc9b53ad5
Revises: d3539f0b9505
Create Date: 2026-05-29 23:13:45.228067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84cc9b53ad5'
down_revision: Union[str, None] = 'd3539f0b9505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('rendez_vous_creneau_id_key'), 'rendez_vous', type_='unique')
    op.create_index('uq_active_rdv_per_creneau', 'rendez_vous', ['creneau_id'], unique=True, postgresql_where=sa.text("statut <> 'annule'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_rdv_per_creneau', table_name='rendez_vous', postgresql_where=sa.text("statut <> 'annule'"))
    op.create_unique_constraint(op.f('rendez_vous_creneau_id_key'), 'rendez_vous', ['creneau_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
