"""initial schema

Revision ID: d3539f0b9505
Revises: 
Create Date: 2026-05-29 22:36:24.110655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3539f0b9505'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('patient', 'medecin', 'admin', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('medecin_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('specialite', sa.String(length=100), nullable=False),
    sa.Column('numero_ordre', sa.String(length=50), nullable=True),
    sa.Column('structure_sante', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_medecin_profiles_specialite'), 'medecin_profiles', ['specialite'], unique=False)
    op.create_index(op.f('ix_medecin_profiles_ville'), 'medecin_profiles', ['ville'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('sexe', sa.Enum('masculin', 'feminin', 'autre', name='sexeenum'), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_table('disponibilites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medecin_id', sa.UUID(), nullable=False),
    sa.Column('debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('statut', sa.Enum('libre', 'reserve', name='statutdisponibilite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecin_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medecin_id', 'debut', name='uq_medecin_debut')
    )
    op.create_index(op.f('ix_disponibilites_medecin_id'), 'disponibilites', ['medecin_id'], unique=False)
    op.create_table('dossiers_medicaux',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('entrees_dossier',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dossier_id', sa.UUID(), nullable=False),
    sa.Column('medecin_id', sa.UUID(), nullable=False),
    sa.Column('type_entree', sa.Enum('consultation', 'ordonnance', 'resultat', 'note', name='typeentree'), nullable=False),
    sa.Column('contenu_chiffre', sa.Text(), nullable=False),
    sa.Column('date_entree', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers_medicaux.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecin_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrees_dossier_dossier_id'), 'entrees_dossier', ['dossier_id'], unique=False)
    op.create_table('rendez_vous',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medecin_id', sa.UUID(), nullable=False),
    sa.Column('creneau_id', sa.UUID(), nullable=False),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('demande', 'confirme', 'annule', 'termine', name='statutrdv'), nullable=False),
    sa.Column('paiement_ref', sa.String(length=100), nullable=True),
    sa.Column('rappel_envoye', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creneau_id'], ['disponibilites.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecin_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creneau_id')
    )
    op.create_index(op.f('ix_rendez_vous_medecin_id'), 'rendez_vous', ['medecin_id'], unique=False)
    op.create_index(op.f('ix_rendez_vous_patient_id'), 'rendez_vous', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rendez_vous_patient_id'), table_name='rendez_vous')
    op.drop_index(op.f('ix_rendez_vous_medecin_id'), table_name='rendez_vous')
    op.drop_table('rendez_vous')
    op.drop_index(op.f('ix_entrees_dossier_dossier_id'), table_name='entrees_dossier')
    op.drop_table('entrees_dossier')
    op.drop_table('dossiers_medicaux')
    op.drop_index(op.f('ix_disponibilites_medecin_id'), table_name='disponibilites')
    op.drop_table('disponibilites')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_medecin_profiles_ville'), table_name='medecin_profiles')
    op.drop_index(op.f('ix_medecin_profiles_specialite'), table_name='medecin_profiles')
    op.drop_table('medecin_profiles')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
