"""doctolib: medecin enriched fields, motifs, notifications

Revision ID: fc5e0416fa80
Revises: c84cc9b53ad5
Create Date: 2026-05-29 23:56:06.932868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5e0416fa80'
down_revision: Union[str, None] = 'c84cc9b53ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('lu', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('motifs_consultation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medecin_id', sa.UUID(), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('duree_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecin_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motifs_consultation_medecin_id'), 'motifs_consultation', ['medecin_id'], unique=False)
    op.add_column('medecin_profiles', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('medecin_profiles', sa.Column('langues', sa.String(length=255), nullable=True))
    op.add_column('medecin_profiles', sa.Column('tarif_fcfa', sa.Integer(), nullable=True))
    op.add_column('medecin_profiles', sa.Column('adresse', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medecin_profiles', 'adresse')
    op.drop_column('medecin_profiles', 'tarif_fcfa')
    op.drop_column('medecin_profiles', 'langues')
    op.drop_column('medecin_profiles', 'bio')
    op.drop_index(op.f('ix_motifs_consultation_medecin_id'), table_name='motifs_consultation')
    op.drop_table('motifs_consultation')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
